kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
      - ls

  - name: rsync
    image: drillster/drone-rsync
    commands:
      - ls
