kind: pipeline
type: docker
name: default

steps:
  - name: listing
    image: alpine
    commands:
      - ls

  - name: rsync
    image: drillster/drone-rsync
    settings:
      host:
        - 172.20.10.2
      user:
        - wzw
      key:
        - nozomi
