kind: pipeline
type: docker
name: default

steps:
  - name: listing
    image: alpine
    commands:
      - ls
      - pwd

  - name: clone_2
    image: alpine/git
    commands:
      - cd /drone/src
      - pwd
      - git clone https://github.com/zheng-wei-wu/Drone_test.git
      - ls
