kind: pipeline
type: docker
name: default

steps:
  - name: listing
    image: alpine
    commands:
      - ls
      - pwd

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
    - name: cache
      path: /cache
    settings:
      rebuild: true
      mount:
        - /drone/src

volumes:
  - name: cache
    host:
      path: /Users/wzw/Desktop/A
